### ISSUE TITLE
Return files paths in product model

### ISSUE THREAD

**Issue by misiek231** [VersatileSoft/Wirtualnik#85]

**Comment by misiek231** [comment]
Czy to jest potrzebne? 
Domyślnie pliki będą zawsze zapisane według schematu "Images/{PublicId}/{Rozmiar}.png"
Szkoda pakować do modelu info które i tak już jest na froncie.

**Comment by kcrg** [comment]
Bez urla do obrazka w modelu będe musiał to w jakiś inny sposób skonsumować = więcej kodu po stronie końcówek = większy narzut na performace. Nie chce wrzucać jakiej kolwiek logiki do wyświetlania danych w cellkach nawet jeśli to tylko łączenie stringów. Model ma być jak najprostrzy w konsumowaniu

**Comment by misiek231** [comment]
Jak masz powiedzy zdj o nazwie 200x300.jpg i 500x800.jpg to albo musze wysłać 2 stringi albo ty i tak musisz zrobić interpolację wielkości jaką chcesz. Więc jak i tak robisz interpolację to chyba możesz tam dorzucić też public id. 5 stringów na jednym itemku to może mało ale razy 50 na raz to już większy ruch w sieci i mniej reuqestów na sekundę.

**Comment by kcrg** [comment]
To prawda ale czy rozmiar obrazka nie powinien być zależny od przeznaczenia modelu? Np. model przeznaczony do listy będzie zawierał tylko jeden rozmiar obrazka, ten mniejszy a model od detailsów będzie zwracać większy obrazek? Czy mam to konsumowac jakoś per typ urządzenia na podstawie zagęszczenia (co niezbyt ma sens jak rozmiarów ma być tylko 6)? Jeśli druga opcja to ok, zwracanie urla do obrazka w modelu jest useless

**Comment by misiek231** [comment]
Done in #84
